sonar.organization=YOUR_ORG_KEY
sonar.projectKey=YOUR_ORG_KEY_gabara-wbt
sonar.projectName=gabara-wbt
sonar.host.url=https://sonarcloud.io
sonar.login=${env.SONAR_TOKEN}
sonar.sources=lib
sonar.exclusions=**/*.g.dart,build/**,test/**,android/**,ios/**,macos/**,windows/**,linux/**,web/**
sonar.language=dart
