name: SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: YOUR_ORG_KEY
          projectKey: YOUR_ORG_KEY_gabara-wbt
          token: ${{ secrets.SONAR_TOKEN }}
